
services:
    db.config:
        class: 'DbBundle\Db\DbConfig'

    # todo: setCacheItemPool
    # todo: setLogger
    db.manager:
        class: 'DbBundle\Db\DbManager'
        arguments: ['@db.config', []]
