language: php

sudo: false

php:
    - 8.0
    - 8.1

services:
    - 'mysql'

before_install:
    - 'mysql -e "CREATE DATABASE IF NOT EXISTS test;"'

install:
    - 'composer install --prefer-source'

matrix:
    fast_finish: true
