language: php

sudo: false

php:
    - 7.1
    - 7.2
    - 7.3

services:
    - 'mysql'

before_install:
    - 'mysql -e "CREATE DATABASE IF NOT EXISTS test;"'

install:
    - 'composer install --prefer-source'

matrix:
    fast_finish: true
